name: Auto Pull on Main Push

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          path: /home/adam/Desktop/distance

      - name: Pull Latest Code
        working-directory: /home/adam/Desktop/distance
        run: |
          git pull origin main